ALTER TABLE restaurants
    ADD COLUMN IF NOT EXISTS is_busy TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS delivery_enabled TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS delivery_radius_km DECIMAL(6, 2) NULL,
    ADD COLUMN IF NOT EXISTS peak_hour_available TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS operations_note VARCHAR(255) NULL;
