ALTER TABLE restaurant_applications
    ADD COLUMN IF NOT EXISTS fssai_number VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS gst_number VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS pan_number VARCHAR(100) NULL;

ALTER TABLE restaurants
    ADD COLUMN IF NOT EXISTS fssai_number VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS gst_number VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS pan_number VARCHAR(100) NULL;
